### PR TITLE
i fixed memes

### PR DESCRIPTION
**Pull request by davidcralph**
wow what a weeb

### CODE REVIEW

**Comment by Cyber28** [comment]
We do not use semicolons in our JS code. We also don't want to log errors in the `commandHandler.js` file either, everything else looks good 👍

**Comment by davidcralph** [comment]
no semicolons

what shit you on

**Comment by davidcralph** [comment]
remove them yourself smh my head

**Comment by Cyber28** [comment]
javascript
fine, just need to remove the console logging in the `commandHandler.js`, i should be able to do that once i figure out how

**Pull request merged**
